FROM python:3.7

RUN apt-get update
RUN apt-get install -y build-essential cmake libboost-all-dev python3-dev

RUN pip install --upgrade pip
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /srv
# COPY lib/ .
# COPY server.py .
COPY . .

EXPOSE 8000
CMD ["python", "server.py"]
